### ISSUE TITLE
Mistwoods update

### ISSUE THREAD

**Issue by jimmyleith** [Pimpmuckl/pimpcasting#4]
Since the new patch I am finding myself unable to bind exec file.cfg in console.
you are still able to switch between .cfgs manually in console however.
https://dev.dota2.com/forum/dota-2/settings/2256946-unable-to-bind-cfg-files-to-hotkey
if you know of a workaround please advise

**Comment by lemps** [comment]
This seems like something hard to get around.

I made a mistake of binding and unbinding position keys to 1-5 in the Dota settings UI and those keys became unusable for me.

Even if they're cleared in the UI or replaced with something else I can no longer rebind the keys.

There is no mention of those keys anywhere in the local settings files of Dota so I assume they're hidden in some cloud settings storage.

**Comment by Pimpmuckl** [comment]
In general, there are three different sort of "keybinds" that Dota seems to have.

- The ones in your settings menu that get synced to your Steam Cloud
- Other keybinds that get synced to your Steam Cloud (like the hero numbers from 0-9)
- Local keybinds that don't get synced and are manipulatable by console commands

The local keybinds never seem to take priority, so if you want to bind something to a key, you need to make sure that the key is not bound to anything else, because the steam cloud setting will take priority.

There is a convar to check for what a key is bound to but I think I had issues with it in the past and I forgot about it.

There's two things you can do:
1. Double check the settings menu and bind say F11 once to an action, then quit Dota, let the cloud sync, then unbind it again and use it as trigger for your execute.
2. Reset your keybinds to defaults (and take a screenshot before!), which sometimes fixes weird inconsistencies with the Steam Cloud keybinds. Those tend to get corrupted if something funky happens (happens to me a lot when producing in China)

**Comment by lemps** [comment]
The second solution worked and I got expected results. It "freed" the bound hotkeys and I could use 1-0 as hero slots once more.

Thanks for the assist and for this awesome config.

**Comment by anonyao** [comment]
> Since the new patch I am finding myself unable to bind exec file.cfg in console. you are still able to switch between .cfgs manually in console however. https://dev.dota2.com/forum/dota-2/settings/2256946-unable-to-bind-cfg-files-to-hotkey if you know of a workaround please advise
i have kinda same problem but i only make "game" scripts ,  and i make other binds if some is taken ,  start your "cfg" with "config"
{
   "bindings" (or random name/titles but then u need to make new cfg files )
   {
//example ;bind "F10" "say HELLO
-------------------------
   }


}

but i was mailed him for help to do all binds /convars/    customs like valve have done with their binds and settings :P and just  delete orginal code inside cfgs and save "config" start{ } end "convars" "bindings" and rename them to "yourautoexec.1cfg" / 2 / 3 save all as : .cfg/vcfg for each file , rememebber to delete DEFAULT_key / dev_keys "cfg files  only your own shall be left start steam / dota2/  then disable cloud / goto launch options " -console ; autoconfig.cfg or -autoconfig.cfg "
start dota2 if u not sure go top console / text exex autoexec.cfg 
then wait ,,, wen u see it load , type restart  
wait , then turn off dota2 remove  -autoconfig / autoconfig from launch opt : then turn cloud : ON  , shutdown steam and restart

**Comment by Pimpmuckl** [comment]
> 
@anonyao 

I have no idea what exactly you mean. 

If there is a problem, please make a new issue and don't spam the old, clearly marked as "outdated" wordpress blog and describe it properly.

But I'll close the issue since the solution works.

**Comment by anonyao** [comment]
i answer @jimmyleith  how i did before i find your scripts :D did your get my message from your homepage? 
My quest was ; 90% of all cfgs i found is written in normal txt. language ,  and my first issue was if i can do all (configs/ scripts/ custom binds / cvars")  in same file ? and if i i can choose to do settingss in other programming language instead of txt extention , like " json / autolit / python / what ever , or do i need a special for dota2 gonna be able to read it ? , @Pimpmuckl 
[user_keys_dev_default1.txt](https://github.com/Pimpmuckl/pimpcasting/files/11103115/user_keys_dev_default1.txt) <----  thats  orginal default_keys with convars from steamcloud but i had change few binds and now i wanna do everything in this cfg 
 ----> [autoexec.cfg.txt](https://github.com/Pimpmuckl/pimpcasting/files/11103270/autoexec.cfg.txt) . (i dont need the CAST) i only wanna have for game cfg , sorry for bad english haha , and the script not done

**Comment by Pimpmuckl** [comment]
> if i i can choose to do settingss in other programming language instead of txt extention , like " json / autolit / python / what ever , or do i need a special for dota2 gonna be able to read it

No, the game only supports exactly the type of configs you see here. 

It's simply how the Source engine handles cfg files that read user configurations.

This is also completely unrelated to my configs, please stop spamming the issue tracker here.
